import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import SessionWrapper from "./component/SessionWarpper";
import { Toaster } from "react-hot-toast";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <SessionWrapper>
    <html lang="en" className={geist.className}>
    <body style={{ background: "#eff6ff" }} className="vsc-initialized">
    <Toaster position="top-right" />
          {children}
          </body>
         </html>
    </SessionWrapper>
  );
}
