import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import SessionWrapper from "./component/SessionWarpper";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <SessionWrapper>
      <html>
      <body style={{ background: "#ebe6e6" }}>
          {children}
          </body>
         </html>
    </SessionWrapper>
  );
}
